Update the Kotlin generator to support KMP projects
rogerluan/arkana pull request #60
Opened 2024-05-23 20:43 UTC by husseinala

# Description

Add Kotlin Multiplatform support by applying the following updates to the Kotlin generator:

1. Update the `arkana.kt.erb` template to ensure the generated Kotlin code is compatible with multiplatform projects by replacing the JVM only function [`ByteArray#toString(...)`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/to-string.html) with its KMP counterpart [`ByeArray#decodeToString()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/decode-to-string.html#decodetostring)
2. Add `is_kotlin_multiplatform_module` as a new yml configuration parameter that changes the generated `build.gradle` file and `SourceSet` folders to a KMP compatible ones when set to `true`.

2024-06-04 02:26 UTC, rogerluan requested changes
Amazing contribution like always, thank you so much! ❤️ 

Just requested some minor improvements but overall this PR is great! 🙌 

Let me know if you have any questions 😊 Also, I apologize for taking so long to get to this PR! I completely missed it in my notifications!

2024-06-06 19:16 UTC, husseinala commented on docs/kotlin-demo.png
@rogerluan nice thank you! I was wondering what tool you used to optimize the images, also for the code window size, I tried to increase the window size but it seems like that's the maximum size https://ray.so/ would allow, so I was wondering if you used a different tool to generate the original image?

2024-06-06 19:16 UTC, husseinala commented on spec/kotlin_code_generator_spec.rb
> +          expect(path(kotlin_sources_dir,  "#{config.namespace}.kt")).to be_file
Oh nice catch! I'm not sure how that happened either 😅

2024-06-08 19:09 UTC, rogerluan commented on docs/kotlin-demo.png
Nope, it was ray.so 🤔 that's weird! I'll check

2024-06-08 19:14 UTC, rogerluan commented on docs/kotlin-demo.png
I just created a new one and it looks similar to the one that we have in `main` (same width apparently, 1840px when exporting at `@2x`):

<img width="261" alt="image" src="https://github.com/rogerluan/arkana/assets/8419048/187dcd75-503a-4ea6-9b35-564c49e0521f">

You can check the source [here](https://ray.so/#code=Ly8gRE8gTk9UIE1PRElGWQovLyBBdXRvbWF0aWNhbGx5IGdlbmVyYXRlZCBieSBBcmthbmEgKGh0dHBzOi8vZ2l0aHViLmNvbS9yb2dlcmx1YW4vYXJrYW5hKQpwYWNrYWdlIGNvbS5hcmthbmFrZXlzCgpvYmplY3QgTXlTZWNyZXRzIHsKICAgIHByaXZhdGUgdmFsIHNhbHQgPSBsaXN0T2YoMHgzZiwgMHhiNiwgMHgyLCAweDMsIDB4YmYsIDB4NTQsIDB4ZjUsIDB4NjcsIDB4OTUsIDB4YywgMHg1NiwgMHg0NywgMHg4NywgMHg1NSwgMHg2MCwgMHg3NCwgMHg2LCAweDc3LCAweDhiLCAweGQ2LCAweDg4LCAweDQxLCAweDk5LCAweGUyLCAweDk3LCAweDkyLCAweDlmLCAweDY4LCAweDdkLCAweDZjLCAweDM5LCAweDY0LCAweGNhLCAweDk4LCAweGU3LCAweDhkLCAweGU4LCAweDllLCAweDFmLCAweGU1LCAweGFkLCAweDQ1LCAweDMyLCAweGFjLCAweGM1LCAweGUxLCAweGY2LCAweDRmLCAweDY3LCAweGNjLCAweDZhLCAweGVlLCAweDY2LCAweGFjLCAweDgwLCAweGVhLCAweDc4LCAweDFiLCAweGQ2LCAweDc4LCAweDQsIDB4OTcsIDB4ZmEsIDB4Y2MpCgogICAgaW50ZXJuYWwgZnVuIGRlY29kZShlbmNvZGVkOiBMaXN0PEludD4sIGNpcGhlcjogTGlzdDxJbnQ-KTogU3RyaW5nIHsKICAgICAgICB2YWwgZGVjb2RlZCA9IGVuY29kZWQubWFwSW5kZXhlZCB7IGluZGV4LCBpdGVtIC0-CiAgICAgICAgICAgIChpdGVtIHhvciBjaXBoZXJbKGluZGV4ICUgY2lwaGVyLnNpemUpXSkudG9CeXRlKCkKICAgICAgICB9LnRvQnl0ZUFycmF5KCkKICAgICAgICByZXR1cm4gZGVjb2RlZC5kZWNvZGVUb1N0cmluZygpCiAgICB9CgogICAgaW50ZXJuYWwgZnVuIGRlY29kZUludChlbmNvZGVkOiBMaXN0PEludD4sIGNpcGhlcjogTGlzdDxJbnQ-KTogSW50IHsKICAgICAgICByZXR1cm4gZGVjb2RlKGVuY29kZWQgPSBlbmNvZGVkLCBjaXBoZXIgPSBjaXBoZXIpLnRvSW50KCkKICAgIH0KCiAgICBpbnRlcm5hbCBmdW4gZGVjb2RlQm9vbGVhbihlbmNvZGVkOiBMaXN0PEludD4sIGNpcGhlcjogTGlzdDxJbnQ-KTogQm9vbGVhbiB7CiAgICAgICAgcmV0dXJuIGRlY29kZShlbmNvZGVkID0gZW5jb2RlZCwgY2lwaGVyID0gY2lwaGVyKS50b0Jvb2xlYW4oKQogICAgfQoKICAgIG9iamVjdCBHbG9iYWwgewogICAgICAgIHZhbCBzb21lQm9vbGVhblNlY3JldDogQm9vbGVhbgogICAgICAgICAgICBnZXQoKSB7CiAgICAgICAgICAgICAgICB2YWwgZW5jb2RlZCA9IGxpc3RPZigweDRiLCAweGM0LCAweDc3LCAweDY2KQogICAgICAgICAgICAgICAgcmV0dXJuIGRlY29kZUJvb2xlYW4oZW5jb2RlZCA9IGVuY29kZWQsIGNpcGhlciA9IHNhbHQpCiAgICAgICAgICAgIH0KCiAgICAgICAgdmFsIHNvbWVJbnRTZWNyZXQ6IEludAogICAgICAgICAgICBnZXQoKSB7CiAgICAgICAgICAgICAgICB2YWwgZW5jb2RlZCA9IGxpc3RPZigweGIsIDB4ODQpCiAgICAgICAgICAgICAgICByZXR1cm4gZGVjb2RlSW50KGVuY29kZWQgPSBlbmNvZGVkLCBjaXBoZXIgPSBzYWx0KQogICAgICAgICAgICB9CgogICAgICAgIHZhbCBteVNlY3JldEFQSUtleTogU3RyaW5nCiAgICAgICAgICAgIGdldCgpIHsKICAgICAgICAgICAgICAgIHZhbCBlbmNvZGVkID0gbGlzdE9mKDB4NiwgMHg4NCwgMHgzMCwgMHgzMCwgMHg4YywgMHg2MywgMHhjNywgMHg1NywgMHhhNiwgMHgzYSwgMHg2ZSwgMHg3MiwgMHhiMywgMHg2MiwgMHg1NywgMHg0MSwgMHgzZSwgMHg0NywgMHhiYywgMHhlZiwgMHhiYSwgMHg3MywgMHhhYSwgMHhkMSwgMHhhMCwgMHhhMCwgMHhhZiwgMHg1YiwgMHg0YiwgMHg1NCwgMHhjLCAweDUwLCAweGZkLCAweGFmLCAweGQyLCAweGI1LCAweGQ4LCAweGE5KQogICAgICAgICAgICAgICAgcmV0dXJuIGRlY29kZShlbmNvZGVkID0gZW5jb2RlZCwgY2lwaGVyID0gc2FsdCkKICAgICAgICAgICAgfQogICAgfQoKICAgIG9iamVjdCBEZXYgOiBNeVNlY3JldHNFbnZpcm9ubWVudCB7CiAgICAgICAgb3ZlcnJpZGUgdmFsIHNlcnZpY2VLZXk6IFN0cmluZwogICAgICAgICAgICBnZXQoKSB7CiAgICAgICAgICAgICAgICB2YWwgZW5jb2RlZCA9IGxpc3RPZigweDRiLCAweGRlLCAweDZiLCAweDcwLCAweDlmLCAweDMwLCAweDkwLCAweDExLCAweGI1LCAweDY3LCAweDMzLCAweDNlLCAweGE3LCAweDNjLCAweDEzLCAweDU0LCAweDc1LCAweDEyLCAweGU4LCAweGE0LCAweGVkLCAweDM1KQogICAgICAgICAgICAgICAgcmV0dXJuIGRlY29kZShlbmNvZGVkID0gZW5jb2RlZCwgY2lwaGVyID0gc2FsdCkKICAgICAgICAgICAgfQogICAgfQoKICAgIG9iamVjdCBTdGFnaW5nIDogTXlTZWNyZXRzRW52aXJvbm1lbnQgewogICAgICAgIG92ZXJyaWRlIHZhbCBzZXJ2aWNlS2V5OiBTdHJpbmcKICAgICAgICAgICAgZ2V0KCkgewogICAgICAgICAgICAgICAgdmFsIGVuY29kZWQgPSBsaXN0T2YoMHg0YiwgMHhkZSwgMHg2YiwgMHg3MCwgMHg5ZiwgMHgyNywgMHg4MSwgMHg2LCAweGYyLCAweDY1LCAweDM4LCAweDIwLCAweGE3LCAweDNlLCAweDUsIDB4ZCwgMHgyNiwgMHgxZSwgMHhmOCwgMHhmNiwgMHhmYiwgMHgyNCwgMHhmYSwgMHg5MCwgMHhmMiwgMHhlNikKICAgICAgICAgICAgICAgIHJldHVybiBkZWNvZGUoZW5jb2RlZCA9IGVuY29kZWQsIGNpcGhlciA9IHNhbHQpCiAgICAgICAgICAgIH0KICAgIH0KfQ&theme=meadow)

Image (already optimized it via TinyPNG):

![ray-so-export-9](https://github.com/rogerluan/arkana/assets/8419048/848c2097-d3fb-423f-8daa-0c1127a57cb3)

Feel free to download and commit this one 🤗

2024-06-09 21:36 UTC, husseinala commented on docs/kotlin-demo.png
Oh thank you for this! I've pushed the updated image, not sure why mine was generating a different width image 🤷🏼‍♂️

2024-06-11 12:21 UTC, rogerluan approved these changes
Again, thanks a lot for this! 🚀 
Great contribution as always!

2024-06-11 12:21 UTC, merged

2024-06-11 12:51 UTC, rogerluan commented
Released in https://github.com/rogerluan/arkana/releases/tag/v2.1.0 🚀